name: Checkout app checks

on:
  push:
    paths:
      - "apps/saleor-app-checkout/**/*"
      - ".github/workflows/saleor-app-checkout.yaml"

jobs:
  tsc-and-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2 # version used by Vercel

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install deps
        run: |
          pnpm i

      - name: Run tsc
        run: |
          pnpm run check-types --scope="saleor-app-checkout"

      - name: Run lint
        run: |
          pnpm run lint --scope="saleor-app-checkout"

      - name: Run tests
        env:
          TEST_MOLLIE_KEY: ${{ secrets.TEST_MOLLIE_KEY }}
          TEST_MOLLIE_PROFILE_ID: ${{ secrets.TEST_MOLLIE_PROFILE_ID }}
          SETTINGS_ENCRYPTION_SECRET: "testng"
        run: |
          pnpm run test --scope="saleor-app-checkout"
